language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x mvnw

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - bbomi0913@gmail.com